export const SKILL_LABELS={
  'p1-photo':'Part 1 · Photos','p2-response':'Part 2 · Question-réponse','p3-conversation':'Part 3 · Conversations','p4-talk':'Part 4 · Talks',
  'p5-grammar':'Part 5 · Grammaire','p6-text':'Part 6 · Texte à compléter','p7-reading':'Part 7 · Compréhension écrite',
  inference:'Inférences',paraphrase:'Paraphrases',detail:'Détails',purpose:'Intention / objectif',vocabulary:'Vocabulaire professionnel',grammar:'Grammaire',timing:'Gestion du temps',distractors:'Distracteurs'
};
function partKey(part){return `p${part}-${part===1?'photo':part===2?'response':part===3?'conversation':part===4?'talk':part===5?'grammar':part===6?'text':'reading'}`;}
function level(m,n){if(n<2)return 'À découvrir';if(m<.45)return 'Critique';if(m<.62)return 'À travailler';if(m<.76)return 'En progression';if(m<.9)return 'Solide';return 'Maîtrisé';}
export function recomputeSkills(questions,attempts){const qmap=new Map(questions.map(q=>[q.id,q]));const map=new Map();for(const a of attempts){const q=qmap.get(a.questionId);if(!q)continue;const keys=[partKey(q.part),...(q.skills||[])];for(const key of keys){const s=map.get(key)||{id:key,attempts:0,correct:0,totalMs:0,mastery:.5};s.attempts++;s.correct+=a.correct?1:0;s.totalMs+=a.timeMs||0;const speed=Math.max(.2,Math.min(1.2,(q.timeTargetSec||30)*1000/Math.max(a.timeMs||1000,1000)));const recent=(a.correct?1:0)*.78+speed*.22;s.mastery=s.mastery*.8+recent*.2;map.set(key,s);}}
  for(const s of map.values()){s.accuracy=s.attempts?s.correct/s.attempts:0;s.avgMs=s.attempts?s.totalMs/s.attempts:0;s.level=level(s.mastery,s.attempts);}
  return [...map.values()];
}
function priorityScore(s){const weakness=1-(s.mastery??.5);const evidence=Math.min(1,(s.attempts||0)/8);return weakness*(.65+.35*evidence)}
export function priorities(skills,limit=3){return [...skills].sort((a,b)=>priorityScore(b)-priorityScore(a)).slice(0,limit);}
export function pickAdaptive(questions,attempts,skills,count=12){const qmapAttempts=new Map();for(const a of attempts) qmapAttempts.set(a.questionId,(qmapAttempts.get(a.questionId)||0)+1);const smap=new Map(skills.map(s=>[s.id,s]));return [...questions].map(q=>{let weakness=1-(smap.get(partKey(q.part))?.mastery??.5);for(const sk of q.skills||[]) weakness=Math.max(weakness,1-(smap.get(sk)?.mastery??.5));const repeat=qmapAttempts.get(q.id)||0;const freshness=1/(1+repeat*.6);const score=weakness*.7+freshness*.25+Math.random()*.05;return {q,score};}).sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.q);}
export function estimatedScores(questions,attempts){const qmap=new Map(questions.map(q=>[q.id,q]));const recent=[...attempts].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,160);const calc=parts=>{const arr=recent.filter(a=>parts.includes(qmap.get(a.questionId)?.part));if(!arr.length) return 5;const acc=arr.filter(a=>a.correct).length/arr.length;return Math.max(5,Math.min(495,Math.round((5+acc*490)/5)*5));};const listening=calc([1,2,3,4]);const reading=calc([5,6,7]);return {listening,reading,total:listening+reading};}
