import {addAttempt,addSession,saveError,saveSkill,saveProfile} from './db.js';
import {recomputeSkills} from './adaptive.js';
import {playQuestionAudio,stopAudio} from './audio.js';
import {PLACEMENT_STAGES} from './curriculum.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,callbacks,session;
export function startSession(s,opts){state=s;callbacks=opts;session={id:crypto.randomUUID(),type:opts.type,questions:opts.questions,index:0,answers:[],startedAt:new Date().toISOString(),t0:Date.now(),qt:Date.now(),placementStage:opts.placementStage??null};renderQ()}
export function startPlacement(s,opts){state=s;callbacks=opts;session={id:crypto.randomUUID(),type:'placement',questions:PLACEMENT_STAGES[0].questions,index:0,answers:[],startedAt:new Date().toISOString(),t0:Date.now(),qt:Date.now(),placementStage:0};renderQ()}
function renderQ(){const q=session.questions[session.index],app=document.getElementById('app');app.innerHTML=`<main class="exercise-shell"><header class="exercise-top"><button id="quit">Fermer</button><div class="exercise-progress"><span style="width:${Math.round((session.index/session.questions.length)*100)}%"></span></div><span>${session.index+1}/${session.questions.length}</span></header><section class="exercise-card">${q.audioScript?.length?'<button class="listen-button" id="listen">▶ Écouter</button>':''}${q.passage?`<div class="reading-passage">${esc(q.passage)}</div>`:''}<div class="exercise-prompt">${esc(q.prompt)}</div><div class="exercise-answers">${q.choices.map((c,i)=>`<button data-a="${i}"><span>${String.fromCharCode(65+i)}</span>${esc(c)}</button>`).join('')}</div></section></main>`;document.getElementById('quit').onclick=()=>{stopAudio();session=null;callbacks.onExit?.()};document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>answer(+b.dataset.a));const l=document.getElementById('listen');if(l)l.onclick=()=>playQuestionAudio(q).catch(()=>{})}
async function answer(selected){const q=session.questions[session.index],ok=selected===q.correctIndex,a={id:crypto.randomUUID(),questionId:q.id,sessionId:session.id,part:q.part,correct:ok,selected,timeMs:Date.now()-session.qt,createdAt:new Date().toISOString(),payload_json:{}};state.attempts.push(a);await addAttempt(a);session.answers.push(a);if(!ok){const old=state.errors.find(x=>x.questionId===q.id),er={id:old?.id||crypto.randomUUID(),questionId:q.id,count:(old?.count||0)+1,updatedAt:new Date().toISOString(),payload_json:{}};old?Object.assign(old,er):state.errors.push(er);await saveError(er)}showCorrection(q,selected,ok)}
function showCorrection(q,selected,ok){const app=document.getElementById('app');app.innerHTML=`<main class="exercise-shell"><section class="exercise-card correction"><span class="result-chip ${ok?'ok':'bad'}">${ok?'Bonne réponse':'À revoir'}</span><div class="exercise-prompt">${esc(q.prompt)}</div><div class="exercise-answers review">${q.choices.map((c,i)=>`<div class="${i===q.correctIndex?'correct':''} ${i===selected&&i!==q.correctIndex?'wrong':''}"><span>${String.fromCharCode(65+i)}</span>${esc(c)}</div>`).join('')}</div><div class="explanation"><strong>À retenir</strong><p>${esc(q.explanation||'Observe la formulation correcte et réessaie-la plus tard.')}</p>${q.transcript?`<small>${esc(q.transcript)}</small>`:''}</div><button class="primary-action full" id="next">${session.index<session.questions.length-1?'Continuer':'Terminer'}</button></section></main>`;document.getElementById('next').onclick=next}
async function next(){if(session.index<session.questions.length-1){session.index++;session.qt=Date.now();renderQ();return}if(session.type==='placement')return finishPlacementStage();await finish()}
async function finishPlacementStage(){const stage=PLACEMENT_STAGES[session.placementStage],ids=new Set(stage.questions.map(q=>q.id)),arr=session.answers.filter(a=>ids.has(a.questionId)),acc=arr.filter(a=>a.correct).length/Math.max(1,arr.length);let result=stage.level;if(acc>=.67&&session.placementStage<PLACEMENT_STAGES.length-1){session.placementStage++;session.questions=PLACEMENT_STAGES[session.placementStage].questions;session.index=0;session.qt=Date.now();return renderQ()}if(acc<.67&&session.placementStage>0)result=PLACEMENT_STAGES[session.placementStage-1].level;state.profile=await saveProfile({...state.profile,cefrLevel:result,onboardingComplete:true});await finish(result)}
async function finish(level=null){const correct=session.answers.filter(x=>x.correct).length,r={id:session.id,type:session.type,startedAt:session.startedAt,endedAt:new Date().toISOString(),total:session.answers.length,correct,durationSec:Math.round((Date.now()-session.t0)/1000),payload_json:{level}};state.sessions.unshift(r);await addSession(r);state.skills=recomputeSkills(state.questions,state.attempts);for(const sk of state.skills)await saveSkill({...sk,updatedAt:new Date().toISOString(),payload_json:{}});const done=session;session=null;document.getElementById('app').innerHTML=`<main class="exercise-shell"><section class="completion-card"><div class="complete-icon">✓</div><h2>${done.type==='placement'?'Niveau évalué':'Séance terminée'}</h2><p>${done.type==='placement'?`Ton parcours démarre au niveau ${(level||state.profile.cefrLevel||'pre-a1').toUpperCase()}.`:`${correct}/${r.total} bonnes réponses`}</p><button class="primary-action full" id="done">Continuer</button></section></main>`;document.getElementById('done').onclick=()=>callbacks.onFinish?.()}
