import {LEVELS,THEMES,LESSONS} from './curriculum.js';
import {SKILL_LABELS} from './adaptive.js';

export const TABS=[['today','Aujourd’hui','⌂'],['learn','Apprendre','▤'],['practice','Pratiquer','▶'],['progress','Progrès','◫'],['profile','Profil','○']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>Math.max(0,Math.min(100,Math.round(n||0)));
const themeIcon=id=>({survival:'✦',identity:'☺',numbers:'123',colors:'◐',food:'☕',hotel:'⌂',travel:'✈',shopping:'▢',smalltalk:'◌',work:'▣',idioms:'“”',phrasal:'↔',collocations:'⛓',pronunciation:'≋',falsefriends:'!'}[id]||'•');
function navItems(route){return TABS.map(([id,label,icon])=>`<button data-nav="${id}" class="${route===id?'active':''}" aria-label="${label}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></button>`).join('')}

export function shell(state,body,title,score){
  const scoreText=score?.evaluated?`${score.total}/990`:'À évaluer';
  return `<div class="adaptive-shell ${localStorage.getItem('navCollapsed')==='1'?'nav-collapsed':''}">
    <aside class="side-nav">
      <div class="brand-row"><div class="app-mark">990</div><div class="brand-copy"><strong>From0to990</strong><small>English · TOEIC</small></div><button class="collapse-btn" data-act="toggle-nav" aria-label="Replier le menu">‹</button></div>
      <nav>${navItems(state.route)}</nav>
      <div class="side-footer"><span class="status-dot ${navigator.onLine?'':'offline'}"></span><span>${navigator.onLine?'Synchronisé':'Hors ligne'}</span></div>
    </aside>
    <main class="app-main">
      <header class="app-header"><div><span class="eyebrow">${state.profile?.cefrLevel?state.profile.cefrLevel.toUpperCase():'PARCOURS PERSONNALISÉ'}</span><h1>${title}</h1></div><button class="score-pill" data-nav="progress">${scoreText}</button></header>
      <div class="tablet-tabs">${navItems(state.route)}</div>
      <div class="page">${body}</div>
    </main>
    <nav class="bottom-tabs">${navItems(state.route)}</nav>
  </div>`;
}

export function onboarding(profile){
  return `<div class="onboarding-wrap"><section class="onboarding-card">
    <div class="app-mark large">990</div><h1>Ton anglais, du premier mot au 990.</h1>
    <p>Crée ton profil d’apprentissage. Ta progression est enregistrée sur cet appareil puis synchronisée automatiquement quand tu es en ligne.</p>
    <div class="form-list">
      <label><span>Prénom ou pseudo</span><input id="on-name" value="${esc(profile?.displayName||'')}" placeholder="Damien"></label>
      <label><span>Objectif TOEIC</span><input id="on-target" type="number" min="10" max="990" step="5" value="${profile?.targetScore||990}"></label>
      <label><span>Temps par jour</span><select id="on-time">${[10,15,20,30,45,60].map(n=>`<option ${n===(profile?.timePerDay||20)?'selected':''} value="${n}">${n} min</option>`).join('')}</select></label>
    </div>
    <button class="primary-action full" data-act="onboard-test">Évaluer mon niveau</button>
    <button class="secondary-action full" data-act="onboard-zero">Je pars de zéro</button>
    <small class="privacy">Cette version est mono-utilisateur : pas de mot de passe à créer pour l’instant. L’authentification multi-appareils pourra être ajoutée au backend sans perdre ta progression.</small>
  </section></div>`;
}

export function today(state,ctx){const L=LESSONS[ctx.nextLesson],score=ctx.score;return `<div class="today-layout">
<section class="today-primary">
  <div class="hello"><div><span class="subtle">Bonjour${state.profile?.displayName?' '+esc(state.profile.displayName):''}</span><h2>${ctx.cefr?`Niveau ${ctx.cefr.toUpperCase()}`:'Prêt à commencer ?'}</h2></div><div class="streak"><span>🔥</span><strong>${ctx.stats.streak}</strong><small>jours</small></div></div>
  <article class="continue-card"><div class="continue-top"><span class="level-chip">${L.level.toUpperCase()}</span><span>${L.minutes} min</span></div><h3>${esc(L.title)}</h3><p>${esc(L.goal)}</p><div class="lesson-progress"><span style="width:${ctx.nextProgress}%"></span></div><button class="primary-action" data-act="lesson" data-id="${ctx.nextLesson}">Continuer</button></article>
  <section class="section-block"><div class="section-title"><h3>Cette semaine</h3><button data-nav="progress">Voir les progrès</button></div><div class="stat-grid">${stat('⏱',ctx.stats.weekMinutes,'minutes')}${stat('✓',ctx.stats.lessons,'leçons')}${stat('★',ctx.stats.xp,'XP')}${stat('◉',ctx.stats.words,'mots vus')}</div></section>
</section>
<aside class="today-secondary"><section class="section-block"><div class="section-title"><h3>Prochaine priorité</h3></div>${ctx.priorities.length?ctx.priorities.slice(0,3).map((p,i)=>`<div class="priority-row"><span class="priority-rank">${i+1}</span><div><strong>${esc(SKILL_LABELS[p.id]||p.id)}</strong><small>${p.attempts||0} essais · ${pct((p.accuracy||0)*100)}%</small></div></div>`).join(''):'<div class="empty-state">Le test de niveau déterminera tes priorités.</div>'}</section>
<section class="section-block toeic-card"><div><span class="subtle">Objectif TOEIC</span><h3>${score.evaluated?score.total+'/990':'À évaluer'}</h3></div><button data-act="toeic-mini">Mini-test</button></section></aside></div>`}
function stat(icon,value,label){return `<div class="stat-tile"><span>${icon}</span><strong>${value}</strong><small>${label}</small></div>`}

export function learn(state,ctx){const byLevel=LEVELS.slice(0,6).map(l=>({...l,themes:THEMES.filter(t=>t.level===l.id)}));return `<div class="learn-head"><div><h2>Parcours d’anglais</h2><p>Suis la progression recommandée ou travaille une situation précise.</p></div><div class="level-badge">${ctx.cefr?ctx.cefr.toUpperCase():'À évaluer'}</div></div><div class="path-list">${byLevel.map(level=>`<section class="path-level ${ctx.cefr===level.id?'current':''}"><div class="level-rail"><span>${level.label}</span><i></i></div><div class="level-content"><div class="level-title"><div><h3>${esc(level.title)}</h3><p>${esc(level.description)}</p></div></div><div class="theme-grid">${level.themes.map(t=>themeCard(t)).join('')||'<div class="coming">Modules avancés en cours d’ajout.</div>'}</div></div></section>`).join('')}</div>`}
function themeCard(t){return `<button class="theme-card" data-nav="theme" data-theme="${t.id}"><div class="theme-icon">${themeIcon(t.id)}</div><div><strong>${esc(t.title)}</strong><small>${esc(t.summary)}</small></div><span class="chev">›</span></button>`}
export function theme(id){const t=THEMES.find(x=>x.id===id);if(!t)return '<div class="empty-state">Thème introuvable.</div>';return `<button class="back-link" data-nav="learn">‹ Apprendre</button><div class="theme-hero"><div class="theme-icon big">${themeIcon(t.id)}</div><div><span class="level-chip">${t.level.toUpperCase()}</span><h2>${esc(t.title)}</h2><p>${esc(t.summary)}</p></div></div><div class="lesson-list">${t.lessons.map((id,i)=>{const L=LESSONS[id];return `<button class="lesson-row" data-act="lesson" data-id="${id}"><span class="lesson-num">${i+1}</span><div><strong>${esc(L.title)}</strong><small>${esc(L.goal)} · ${L.minutes} min</small></div><span class="chev">›</span></button>`}).join('')}</div>`}

export function practice(){return `<div class="practice-layout"><section class="section-block"><div class="section-title"><h3>Entraînement recommandé</h3></div><p class="lead">Révision, vocabulaire, compréhension et TOEIC selon tes faiblesses.</p><button class="primary-action" data-act="quick-general">Démarrer 12 questions</button></section><section class="section-block"><div class="section-title"><h3>Durée</h3></div><div class="duration-row">${[10,20,30,45,60].map(n=>`<button data-act="timed-general" data-min="${n}">${n}<small>min</small></button>`).join('')}</div></section><section class="section-block"><div class="section-title"><h3>TOEIC</h3></div><div class="practice-options"><button data-act="toeic-mini"><strong>Mini-test</strong><small>rapide, mixte</small></button><button data-act="toeic-listening"><strong>Listening</strong><small>Parts 1–4</small></button><button data-act="toeic-reading"><strong>Reading</strong><small>Parts 5–7</small></button><button data-act="toeic-full"><strong>Blanc complet</strong><small>200 questions</small></button></div></section></div>`}

export function progress(state,ctx){const totalPct=ctx.score.evaluated?pct(ctx.score.total/9.9):0,levelIndex=Math.max(0,LEVELS.findIndex(l=>l.id===ctx.cefr));return `<div class="progress-layout"><section class="progress-hero"><div class="ring" style="--p:${ctx.stats.weekGoalPct}"><div><strong>${ctx.stats.weekMinutes}</strong><small>/ ${ctx.weekGoal} min</small></div></div><div><span class="subtle">Objectif hebdomadaire</span><h2>${ctx.stats.weekGoalPct>=100?'Objectif atteint !':'Continue comme ça'}</h2><p>${ctx.stats.streak} jour${ctx.stats.streak>1?'s':''} de série · ${ctx.stats.xp} XP</p></div></section><div class="dashboard-grid"><section class="section-block"><div class="section-title"><h3>Niveau d’anglais</h3></div><div class="cefr-track">${LEVELS.slice(0,6).map((l,i)=>`<div class="${i<=levelIndex?'done':''} ${l.id===ctx.cefr?'current':''}"><span>${l.label}</span><i></i></div>`).join('')}</div></section><section class="section-block"><div class="section-title"><h3>TOEIC</h3><span>${ctx.score.evaluated?ctx.score.total+'/990':'Non évalué'}</span></div><div class="bar large"><span style="width:${totalPct}%"></span></div><div class="split-stats"><div><strong>${ctx.score.listening??'—'}</strong><small>Listening</small></div><div><strong>${ctx.score.reading??'—'}</strong><small>Reading</small></div></div></section><section class="section-block wide"><div class="section-title"><h3>Ce que tu as amélioré</h3></div>${ctx.gains.length?ctx.gains.map(g=>`<div class="gain-row"><div><strong>${esc(SKILL_LABELS[g.id]||g.id)}</strong><small>${g.attempts} essais</small></div><span>+${g.delta}%</span></div>`).join(''):'<div class="empty-state">Tes progrès apparaîtront après quelques séances.</div>'}</section><section class="section-block"><div class="section-title"><h3>Vocabulaire</h3></div><div class="big-stat">${ctx.stats.words}</div><p>mots et expressions rencontrés</p><button class="text-action" data-nav="vocab">Travailler par thème</button></section><section class="section-block"><div class="section-title"><h3>Habitudes</h3></div><div class="split-stats"><div><strong>${ctx.stats.lessons}</strong><small>leçons</small></div><div><strong>${ctx.stats.sessions}</strong><small>séances</small></div></div></section></div></div>`}
export function vocab(){const featured=THEMES.filter(t=>['idioms','phrasal','collocations','falsefriends','work','travel','food','hotel'].includes(t.id));return `<div class="learn-head"><div><h2>Vocabulaire & expressions</h2><p>Par situation, niveau et type d’expression.</p></div></div><div class="theme-grid vocab-grid">${featured.map(themeCard).join('')}</div>`}
export function profile(state){return `<div class="profile-layout"><section class="section-block profile-summary"><div class="profile-avatar">${esc((state.profile.displayName||'?').slice(0,1).toUpperCase())}</div><h2>${esc(state.profile.displayName||'Mon profil')}</h2><p>${state.profile.cefrLevel?state.profile.cefrLevel.toUpperCase():'Niveau non évalué'} · objectif ${state.profile.targetScore||990}</p></section><section class="settings-list"><label><span>Prénom ou pseudo</span><input id="set-name" value="${esc(state.profile.displayName||'')}"></label><label><span>Objectif TOEIC</span><input id="set-target" type="number" min="10" max="990" value="${state.profile.targetScore||990}"></label><label><span>Temps par jour</span><select id="set-time">${[10,15,20,30,45,60].map(n=>`<option ${n===(state.profile.timePerDay||20)?'selected':''}>${n}</option>`).join('')}</select></label><button class="primary-action" data-act="save-profile">Enregistrer</button></section><section class="settings-list"><div><span>Synchronisation</span><small>${navigator.onLine?'En ligne':'Hors ligne'} · ${state.sync?.pending||0} événement(s) en attente</small></div><button class="secondary-action" data-act="sync">Synchroniser maintenant</button></section></div>`}
