import {access,readFile} from 'node:fs/promises';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const exec=promisify(execFile),root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const files=['src/index.html','src/app.js','src/styles.css','src/styles/base.css','src/styles/learning.css','src/styles/session.css','src/styles/responsive.css','src/lib/db.js','src/lib/adaptive.js','src/lib/audio.js','src/lib/sync.js','src/lib/curriculum.js','src/lib/curriculum-extra.js','src/lib/curriculum-teaching.js','src/lib/curriculum-advanced.js','src/lib/randomize.js','src/lib/ui-admin.js','src/lib/ui-auth.js','src/lib/auth.js','src/lib/theme.js','src/lib/icons.js','src/lib/ui-shell.js','src/lib/ui-today.js','src/lib/ui-learn.js','src/lib/ui-progress.js','src/lib/session.js','src/lib/analytics.js','public/sw.js','public/manifest.webmanifest','backend-contract/openapi.yaml','backend-contract/schema.sql','backend-contract/migrations/002_auth.sql','backend-contract/AUTH_V2.md','scripts/generate-content.mjs','scripts/export-audio-spec.mjs','scripts/validate-curriculum.mjs','scripts/validate-randomization.mjs','scripts/validate-ui-auth.mjs'];
for(const f of files)await access(resolve(root,f));
for(const f of files.filter(f=>f.endsWith('.js')||f.endsWith('.mjs')))await exec(process.execPath,['--check',resolve(root,f)]);
await exec(process.execPath,[resolve(root,'scripts/validate-curriculum.mjs')]);
await exec(process.execPath,[resolve(root,'scripts/validate-randomization.mjs')]);
await exec(process.execPath,[resolve(root,'scripts/validate-ui-auth.mjs')]);
const manifest=JSON.parse(await readFile(resolve(root,'public/manifest.webmanifest'),'utf8'));if(!manifest.name||!manifest.start_url)throw new Error('Invalid manifest');
console.log('Checks OK');
